# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100)),
                ('localite', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1', 'offre'), ('2', 'demande')], max_length=2)),
                ('categories', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('prix', models.CharField(max_length=10)),
                ('Numeros', models.CharField(max_length=10)),
                ('photo1', models.ImageField(upload_to='images/')),
                ('photo2', models.ImageField(upload_to='images/')),
                ('photo3', models.ImageField(upload_to='images/')),
                ('photo4', models.ImageField(upload_to='images/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
